### PR TITLE
Editor line

### PR DESCRIPTION
**Pull request by lassik**

### CODE REVIEW

**Comment by arthurgleckler** [comment]
This removes the author's name.  It's consistent with other SRFIs, but that's not a good enough reason to remove his name from the bottom.

**Comment by lassik** [comment]
His name still remains prominently at the top, right after the title as in all other SRFIs.

There are a 25 other SRFIs with an `Author:` line at the bottom (`grep -F Author: srfi-*.html`). That's only 14% of all SRFIs. In the rest of those, there's a link to the author's email address. This one doesn't have a link, so the `Author:` line at the bottom contains exactly the same information as the `Author` heading at the top.

**Comment by lassik** [comment]
Just noticed that the `Status` heading is also missing from the top (though the status information is there).

**Comment by arthurgleckler** [comment]
I'm still not willing to remove the Author line from the bottom.  The author put it there, and it's such a little thing to leave it.

Everything else looks good, and adding the Status heading would be fine.

Thanks.

**Comment by lassik** [comment]
Fine. I pushed the updated changes.

**Comment by arthurgleckler** [comment]
Thank you for doing this.

**Pull request merged**
